
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqtxpbxoahfuuardbrmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxdHhwYnhvYWhmdXVhcmRicm1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNTU3MDIsImV4cCI6MjA1ODYzMTcwMn0.sNIBtse6HfYuZ50DCm-vfgy03HPWJ9BkMtaK6_LP4kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
