
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnoxdbvpheowgugeyyfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZub3hkYnZwaGVvd2d1Z2V5eWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NzUxMTksImV4cCI6MjA2MTM1MTExOX0.uPjUDPr3PaTyWgjBSUrhXIrOHbw1DFVWyaU6q02YowM";

// Define the extended types for the new tables
type ForumCategory = {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  required_tier: string;
  created_at: string;
};

type ForumTopic = {
  id: string;
  title: string;
  content: string;
  user_id: string;
  category_id: string;
  created_at: string;
  updated_at: string;
  views: number;
  is_pinned: boolean;
  is_locked: boolean;
  is_public: boolean;
};

type ForumReply = {
  id: string;
  topic_id: string;
  user_id: string;
  content: string;
  created_at: string;
  updated_at: string;
  is_solution: boolean;
};

type ForumGroup = {
  id: string;
  name: string;
  description: string;
  category: string;
  tier_required: string;
  is_private: boolean;
  created_at: string;
  member_count: number;
  created_by: string;
};

type CourseFeedback = {
  id: string;
  course_id: number;
  user_id: string;
  comment: string | null;
  rating: number | null;
  created_at: string;
};

// Extend the original Database type to include our new tables
export type ExtendedDatabase = Database & {
  public: {
    Tables: {
      forum_categories: {
        Row: ForumCategory;
        Insert: Omit<ForumCategory, 'id' | 'created_at'> & { id?: string; created_at?: string };
        Update: Partial<Omit<ForumCategory, 'id' | 'created_at'>>;
      };
      forum_topics: {
        Row: ForumTopic;
        Insert: Omit<ForumTopic, 'id' | 'created_at' | 'updated_at' | 'views'> & 
                { id?: string; created_at?: string; updated_at?: string; views?: number };
        Update: Partial<Omit<ForumTopic, 'id' | 'created_at'>>;
      };
      forum_replies: {
        Row: ForumReply;
        Insert: Omit<ForumReply, 'id' | 'created_at' | 'updated_at'> & 
                { id?: string; created_at?: string; updated_at?: string };
        Update: Partial<Omit<ForumReply, 'id' | 'created_at'>>;
      };
      forum_groups: {
        Row: ForumGroup;
        Insert: Omit<ForumGroup, 'id' | 'created_at' | 'member_count'> & 
                { id?: string; created_at?: string; member_count?: number };
        Update: Partial<Omit<ForumGroup, 'id' | 'created_at'>>;
      };
      course_feedback: {
        Row: CourseFeedback;
        Insert: Omit<CourseFeedback, 'id' | 'created_at'> & { id?: string; created_at?: string };
        Update: Partial<Omit<CourseFeedback, 'id' | 'created_at'>>;
      };
    } & Database['public']['Tables'];
  };
};

// Create and export the extended Supabase client
export const supabase = createClient<ExtendedDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
